CREATE TABLE StoredGuardData(
    UserName TEXT PRIMARY KEY NOT NULL,
    Data TEXT NOT NULL
) STRICT;

CREATE TABLE ProgramRun(
    Id INTEGER PRIMARY KEY NOT NULL,
    StartedAt TEXT NOT NULL
) STRICT;

CREATE TABLE ReceivedGCMessage(
    Id INTEGER PRIMARY KEY NOT NULL,
    ReceivedAt TEXT NOT NULL,
    ReceivedOnRun INTEGER NOT NULL REFERENCES ProgramRun(Id) ON DELETE RESTRICT,
    Protobuf INTEGER NOT NULL,
    MsgType INTEGER NOT NULL,
    Data BLOB NOT NULL
) STRICT;
